[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
sepolia = "${BLAST_TESTNET_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "168587773", url = "${SCAN_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
